version: "3"
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8005:8000  # ホストマシンのポート8005を、docker内のポート8000に接続する
      - 8080:8080  #　ホストマシンのポート8080を、docker内のポート8080に接続する (コンテナ内のappディレクトリ内でstreamlit run app.py --server.port 8080)